# fly.toml app configuration file generated for cron-manager on 2024-04-11T14:24:13-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cron-manager'
primary_region = 'ord'

[[mounts]]
  source = 'data'
  destination = '/data'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[checks]
  [checks.cron]
    grace_period = "30s"
    interval = "20s"
    method = "get"
    path = "/flycheck/cron"
    port = 5500
    timeout = "5s"
    type = "http"
